---
title: "MATH 216 Homework 2 Shiny App"
author: "Kyra Gray"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(babynames)
library(ggplot2movies)
library(forcats)
library(tidyr)
library(readr)
```


## Inputs and Outputs

You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

```{r eruptions, echo=FALSE}

inputPanel(
  #Select Genre
  radioButtons("Genre", "Genre:", c("Comedy"="Comedy", "Not Comedy"= "Not Comedy"))
)

renderPlot({
  
movies2 <- movies %>% 
  mutate(Genre = ifelse(Comedy == 1, "Comedy", "Not Comedy")) %>% 
  filter(!is.na(budget)) %>% 
  filter(Genre == input$Genre) 

ggplot(data=movies2, aes(x=budget, y=rating)) +
  geom_point() +
  geom_smooth() +
  labs(x="Movie Budget", y="Average Movie Rating", title="Relationship between Movie Budget and Movie Rating")

})
```
